# ==============================================================================
# Model Parameter Optimization Workflow via Simulated Annealing (SANN)
# Author: Apurv Srivastav
# Description: Optimizes single-cell phenotypic switching parameters by
#              minimizing weighted residual distances (Mean and CV) between
#              bootstrapped experimental data and distribution-matched 
#              Gillespie simulations.
# ==============================================================================

# --- 1. DEPENDENCIES ---
library(readxl)
library(dplyr)
library(purrr)
library(tidyr)

# --- 2. GLOBAL HYPERPARAMETERS & SETTINGS ---
set.seed(42)

# Fixed Biological & Simulation Constraints
GROWTH_RATE   <- log(2) / 18  
DOUBLING_TIME <- 14.4
T_END_SIM     <- 144     
KOFF_CONSTANT <- 0.028

# Optimization & Resource Configuration
OPT_NUM_COLONIES <- 5000  # Size of simulated testing pool per objective function call
BOOT_ITERATIONS  <- 1000  # Number of bootstrap resamples for experimental baseline
SANN_MAX_ITER    <- 100   # Optimization iterations (Increase for final convergence runs)
LAMBDA_WEIGHT    <- 1.0   # Scale factor balancing Mean vs. CV residuals

# Data Pipeline Configuration
DATA_PATH  <- "C:/Users/apurv/OneDrive/Desktop/Data Analysis/rate switch/IL! and CD36 fractions.xlsx"
DATA_SHEET <- "Cd36 fractions"
EPSILON    <- 1e-4

# --- 3. INPUT DATA PREPARATION ---

message("Loading and cleaning raw experimental benchmarks...")
df_raw <- read_excel(DATA_PATH, sheet = DATA_SHEET, col_names = TRUE)
df_filtered <- df_raw[, colSums(is.na(df_raw)) != nrow(df_raw)]

# Process raw values to avoid numerical edge errors near 0 or 1
CD36_Mock_fraction <- df_filtered %>%
  select(log2Number = 1, FractionON = 2) %>%
  mutate(
    log2Number = as.numeric(log2Number),
    FractionON = as.numeric(FractionON)
  ) %>%
  na.omit() %>%
  mutate(FractionON = pmin(pmax(FractionON, EPSILON), 1 - EPSILON))

message("Calculating weighted bootstrap profiles from experimental targets...")
final_stats_exp <- CD36_Mock_fraction %>%
  mutate(log2_group = floor(log2Number)) %>%
  filter(log2_group >= 2 & log2_group <= 10) %>%
  split(.$log2_group) %>%
  map_df(~ {
    group_data <- .x
    
    # Stratified empirical sampling
    boot_stats <- replicate(BOOT_ITERATIONS, {
      sample_idx <- sample(seq_len(nrow(group_data)), replace = TRUE)
      resample   <- group_data[sample_idx, ]
      m  <- mean(resample$FractionON, na.rm = TRUE)
      v  <- sd(resample$FractionON, na.rm = TRUE) / m
      c(m = m, cv = v)
    }) %>% 
      t() %>% 
      as.data.frame()
    
    # Return weighted penalty matrices based on inverse width of 95% CIs
    data.frame(
      log2_group  = unique(group_data$log2_group),
      mean_val    = mean(boot_stats$m, na.rm = TRUE),
      cv_val      = mean(boot_stats$cv, na.rm = TRUE),
      mean_weight = 1 / (quantile(boot_stats$m, 0.975) - quantile(boot_stats$m, 0.025)),
      cv_weight   = 1 / (quantile(boot_stats$cv, 0.975) - quantile(boot_stats$cv, 0.025))
    )
  })

# --- 4. MODEL MECHANISM FUNCTIONS ---

#' Gillespie Engine with Size-Dependent Phenotypic Transition Kinetics
#' @return Numeric vector containing final c(n_on, n_off)
grow_colony <- function(init, tend, kmin, kmax_val, K, n, koff_val) {
  n_on <- init[1]; n_off <- init[2]; t <- 0
  
  while (t < tend) {
    N <- n_on + n_off
    if (N <= 0) break
    
    curr_kon <- kmin + (kmax_val - kmin) * (N^n / (K^n + N^n))
    
    props <- c(
      GROWTH_RATE * n_on,  # Birth ON
      GROWTH_RATE * n_off, # Birth OFF
      koff_val * n_on,     # Switch ON -> OFF
      curr_kon * n_off     # Switch OFF -> ON
    )
    p_sum <- sum(props)
    if (is.na(p_sum) || p_sum <= 0) break
    
    t <- t + rexp(1, p_sum)
    if (t > tend) break
    
    rand <- runif(1) * p_sum
    if (rand <= props[1]) {
      n_on <- n_on + 1
    } else if (rand <= sum(props[1:2])) {
      n_off <- n_off + 1
    } else if (rand <= sum(props[1:3])) {
      n_on <- n_on - 1; n_off <- n_off + 1
    } else {
      n_on <- n_on + 1; n_off <- n_off - 1
    }
  }
  return(c(n_on = n_on, n_off = n_off))
}

# --- 5. MATHEMATICAL LOSS/OBJECTIVE FUNCTION ---

#' Loss Function Computing Weighted Residual Discrepancies
#' @param params Vector containing candidate variables generated by optimizer
#' @return Scalar evaluation metric representing total squared residual distance
objective_function <- function(params) {
  # Enforce parameter boundaries using absolute values
  kmin_on_test    <- abs(params[1])
  K_param_test    <- abs(params[2])
  n_hill_test     <- abs(params[3])
  alpha_k_test    <- abs(params[4])
  beta_k_test     <- abs(params[5])
  kmax_scale_test <- abs(params[6])
  
  # Run a temporary testing universe using the proposed configurations
  results_pool <- map_df(1:OPT_NUM_COLONIES, ~ {
    colony_kmax_on <- rbeta(1, alpha_k_test, beta_k_test) * kmax_scale_test
    init <- if(runif(1) <= 0.075) c(1, 0) else c(0, 1)
    
    out <- grow_colony(init, T_END_SIM, kmin_on_test, colony_kmax_on, 
                       K_param_test, n_hill_test, KOFF_CONSTANT)
    tot <- sum(out)
    data.frame(log2_N = log2(tot), Fraction_ON = if(tot > 0) out[1]/tot else 0)
  }) %>% 
    filter(log2_N > 0)
  
  # Map simulated data structures onto the exact empirical experimental profile
  matched_indices <- map_int(CD36_Mock_fraction$log2Number, function(exp_val) {
    which.min(abs(results_pool$log2_N - exp_val))
  })
  
  results_matched <- results_pool[matched_indices, ] %>%
    mutate(log2_group = floor(log2_N))
  
  # Compute statistical profiles of matched distributions
  sim_stats <- results_matched %>%
    group_by(log2_group) %>%
    summarise(m  = mean(Fraction_ON), 
              cv = if(m > 0) sd(Fraction_ON)/m else 0, 
              .groups = "drop")
  
  comparison <- inner_join(final_stats_exp, sim_stats, by = "log2_group")
  if(nrow(comparison) == 0) return(9999) 
  
  # Score candidate via weighted least squares residuals
  mean_resid <- sum(((comparison$mean_val - comparison$m)^2) * comparison$mean_weight, na.rm = TRUE)
  cv_resid   <- sum(((comparison$cv_val - comparison$cv)^2) * comparison$cv_weight, na.rm = TRUE)
  
  return((mean_resid * LAMBDA_WEIGHT) + cv_resid)
}

# --- 6. OPTIMIZATION RUNNER ROUTINE ---

# Seed standard baseline parameters configuration
initial_guess <- c(kmin_on = 0.0016, K = 2^6.4, n = 10, alpha = 0.24, beta = 1.15, scale = 0.19)

# Proportional jump-step scales across parameter spaces
p_scale <- c(0.0005, 5, 0.5, 0.1, 0.1, 0.01)

message("Starting optimization routine... this might take a significant timeframe.")

fit_results <- optim(
  par     = initial_guess, 
  fn      = objective_function, 
  method  = "SANN", 
  control = list(
    maxit    = SANN_MAX_ITER,    
    trace    = 1,      
    parscale = p_scale
  )
)

# --- 7. EXTRACTION AND SUMMARY OUTPUTS ---
message("\nOptimization process complete.")
best_params <- abs(fit_results$par)

print("--- Optimized Parameter Results ---")
print(best_params)